# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1okmDxcpotgy7u0CEtV-tIHnn0uP7wBIM
"""

!git clone https://github.com/AvivSham/pFedHN

cd /content/pFedHN

pip install -e

cd experiments/pfedhn

pip install pt-trainer